### ISSUE TITLE
关于机器人鉴权

### ISSUE THREAD

**Issue by scatking** [Taosky/telegram-search-bot#11]
## 问题描述
似乎只要机器人开始使用以后，可以通过私聊机器人@它进行搜索，这样只要任意一个用户知道机器人的 名称就可以查询相关群聊记录了，有一定的风险。
![图片](https://user-images.githubusercontent.com/34273647/153595724-bf44e6bc-a15e-4e2e-95d0-28bb250dc59e.png)

## 解决方案
我对TG机器人的权限相关不是很清楚：
* 如果机器人能主动获取群聊中用户的id的话，可以定时让机器人获取绑定的群聊的所有用户的userid并记录，只允许群里的用户请求搜索。
* 如果机器人没有主动获取userid权限的话，可以在机器人创建的时候绑定一个管理员，由管理员进行第一次的添加。后续通过进群退群事件来自动更新
---

优先度不算很高

**Comment by Taosky** [comment]
这个问题不用担心，用户@bot产生的请求包含用户id，[在这里](https://github.com/Taosky/telegram-search-bot/blob/7bfc4da9b60bddc31e84432554b3c49279d46f95/user_handlers/msg_search.py#L44)会判断用户是否属于目标群组，非群内用户是看不到记录的。另外TG的@bot功能在任意的聊天对话框中都能使用。

**Comment by scatking** [comment]
我这个测试号就不是群组人员,但是能搜索到

**Comment by Taosky** [comment]
> 我这个测试号就不是群组人员,但是能搜索到

确实有这个问题，应该是之前升级`python-telegram-bot`后API有变化，没有进行修改，在最新的提交中修复了。
