### ISSUE TITLE
请问按照设置webhook以后，无法收到消息

### ISSUE THREAD

**Issue by CoffeeCodex** [Taosky/telegram-search-bot#13]
getWebhookinfo显示SSL error {error:0A000086:SSL routines::certificate verify failed} 请问是什么原因

**Comment by CoffeeCodex** [comment]
caddy ssl 不用 internal 就又可以了。。

**Comment by scatking** [comment]
internal 是自签名证书，又不受信任。
使用internal的话需要配合cloudflare的ssl代理才行
