### ISSUE TITLE
历史记录导入问题

### ISSUE THREAD

**Issue by scatking** [Taosky/telegram-search-bot#15]
https://github.com/Taosky/telegram-search-bot/blob/ed597d4fa694d3ed63c0a829d787f29221361c99/web_manager.py#L37

这里遍历messages后检测 user是否在'from_id'中，但是有些特殊事件（比如加群，退群）是没有'from_id'的而是'actor_id'，遍历到这种字段会直接报错：
```
  {
   "id": -000000,
   "type": "service",
   "date": "2022-04-29T21:21:41",
   "actor": "测试号",
   "actor_id": "user5555",
   "action": "join_group_by_link",
   "inviter": "Group",
   "text": ""
  }
```
```
[2022-06-15 03:53:09,020] ERROR in app: Exception on / [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "web_manager.py", line 92, in upload_file
    success_count, fail_count, fail_messages = insert_messages(history_json['id'],history_json['messages'])
  File "web_manager.py", line 37, in insert_messages
    if 'user' not in message['from_id']:
KeyError: 'from_id'
192.168.208.1 - - [15/Jun/2022 03:53:09] "POST / HTTP/1.1" 500 -
```
解决方案：
写一个try或者先判断'from_id'是否在字段里:
```
    if 'from_id' not in message :
        continue
    elif 'user' not in message ['from_id']:
        continue
```

**Comment by scatking** [comment]
![图片](https://user-images.githubusercontent.com/34273647/173736183-1fefb4bf-3fc2-4891-82b0-b1fd48e7dc05.png)
另外导入的表好像在message里面，但是现在记录的是在chat里，导致导入的信息无法搜索

**Comment by scatking** [comment]
另外bot自己记录的chat的id是-100xxxx
导入的chatid是xxxxx
好像也会导致无法搜索

**Comment by Taosky** [comment]
> 

chat id应该是唯一的吧，导入的id和实际的不一致吗？

**Comment by scatking** [comment]
> > 
> 
> chat id应该是唯一的吧，导入的id和实际的不一致吗？

导入的chat_id 是 123456789
然后bot记录的消息的chat_id 是 -100123456789
数据库里体现如下：
![图片](https://user-images.githubusercontent.com/34273647/173752968-d05573d8-ff9e-4818-a781-21c9d032c893.png)

**Comment by scatking** [comment]
> > 
> 
> chat id应该是唯一的吧，导入的id和实际的不一致吗？

导入的chat_id 是 123456789
然后bot记录的消息的chat_id 是 -100123456789
数据库里体现如下：
![图片](https://user-images.githubusercontent.com/34273647/173753239-165f6237-0466-4778-9c29-489af5ae54ce.png)

**Comment by Taosky** [comment]
> > > 
> > 
> > 
> > chat id应该是唯一的吧，导入的id和实际的不一致吗？
> 
> 导入的chat_id 是 123456789 然后bot记录的消息的chat_id 是 -100123456789 数据库里体现如下： ![图片](https://user-images.githubusercontent.com/34273647/173753239-165f6237-0466-4778-9c29-489af5ae54ce.png)

确实是，可能是因为变成supergroup，chat id会多个-100，导出还是原来的chat id。这几个问题已经提交了修复，你试下，因为数据表变了，之前的记录要重新导入。

**Comment by scatking** [comment]
https://github.com/Taosky/telegram-search-bot/blob/a461b6cda5d88c63c0ab4a75cc84859edda27b05/web_manager.py#L19
这里 new chat 的chat id 还是没有修改..
另外这里似乎有两个一样的判断

**Comment by Taosky** [comment]
> https://github.com/Taosky/telegram-search-bot/blob/a461b6cda5d88c63c0ab4a75cc84859edda27b05/web_manager.py#L19
> 
> 
> 这里 new chat 的chat id 还是没有修改..
> 另外这里似乎有两个一样的判断

修改了，判断是不是小于0，不是的话就加上-100

**Comment by scatking** [comment]
测试可用
