### ISSUE TITLE
没看懂该怎么用，是要群管理员才能用吗

### ISSUE THREAD

**Issue by animationplayer** [Taosky/telegram-search-bot#28]
感觉readme有点抽象。完全没看懂。
我关注了@tgsearchtestbot，但是按图片的用法，只转圈，转完了不显示搜索结果

是要找[@botfather](https://t.me/botfather)做一个机器人吗？
还是@tgsearchtestbot要在群里面？

**Comment by Taosky** [comment]
是的，需要自建bot，然后用一台能连上tg的机器去跑这个镜像。

**Comment by animationplayer** [comment]
> 是的，需要自建bot，然后用一台能连上tg的机器去跑这个镜像。

需要机器人在群里吗

**Comment by Taosky** [comment]
> > 是的，需要自建bot，然后用一台能连上tg的机器去跑这个镜像。
> 
> 需要机器人在群里吗

是的，需要管理员拉进群，还要有读消息权限。
