### ISSUE TITLE
你好, 我按照quick-start方式创建的机器人, log一直显示"尚未登陆", 请问正常吗?

### ISSUE THREAD

**Issue by efaun** [Taosky/telegram-search-bot#34]
日志:

![image](https://github.com/Taosky/telegram-search-bot/assets/13315821/986b123a-a30e-4e0c-97bc-b5728a38fdc0)

yml:  (除修改BOT_TOKEN为自己的以外没动其他的配置, 功能一切正常, 除了一直弹日志)

version: "3.9"
services:
    tgbot:
        container_name: tgbot
        image: ghcr.io/taosky/telegram-search-bot:latest
        restart: always
        volumes:
            - ./:/app/config
        ports:
            - "5006:5006"
            - "9968:9968"
        environment:
            # userbot模式, 无需拉机器人进群, 但需要登陆用户为群组成员 (中间商传递消息)
            - USER_BOT=0
            - USER_BOT_API_ID=1234567
            - USER_BOT_API_HASH=xxxxxxxxx
            # bot运行模式
            - BOT_MODE=polling  # polling / webhook (webhook模式请查看Caddyfile)
            - BOT_TOKEN=63470**-dndFHA # Bot Token
            - CACHE_TIME=300 # 一般无需修改
            # 如使用polling模式, 下面的内容不用修改
            - URL_PATH=test     # webhook模式的路径
            - HOOK_URL=https://hook.example.xyz/test # webhook完整url

    # 可创建多个bot容器, 需要自行修改使用新的配置文件夹
    #  tgbot2:
    #   container_name: tgbot
    #     image: ghcr.io/taosky/telegram-search-bot:latest
    #     restart: always
    #     volumes:
    #     ......

    # webhook模式需要用Caddy反代(可不使用自行处理)
    # caddy:
    #     container_name: caddy
    #     image: caddy:2-alpine
    #     restart: unless-stopped
    #     volumes:
    #         - ./Caddyfile:/etc/caddy/Caddyfile
    #     network_mode: "host"

**Comment by Taosky** [comment]
这个应该是userbot模式才会需要用户登录，忘记加判断了，影响是没有的。刚刚解决了这个问题，可以用`docker-compose pull` 和 `docker-compose up -d --remove-orphans`更新一下。

**Comment by efaun** [comment]
> 

👌
