### ISSUE TITLE
如何添加bot到频道

### ISSUE THREAD

**Issue by LiHang941** [Taosky/telegram-search-bot#35]
使用的userBot模式
目前 /start 频道ID，但是搜索全是那个20个图片，有点茫然

**Comment by LiHang941** [comment]
研究了一下代码，看起来必须bot加入了群组才能收集信息

**Comment by Taosky** [comment]
是的，没有适配过频道。

**Comment by LiHang941** [comment]
谢谢回复，用这个项目已经解决问题了
https://github.com/SharzyL/tg_searcher
