### ISSUE TITLE
link似乎有问题

### ISSUE THREAD

**Issue by lancer-wang** [Taosky/telegram-search-bot#41]
![image](https://github.com/Taosky/telegram-search-bot/assets/69783837/a87066ab-06fc-466d-a36b-c0086884031c)

点开查询之后看到这个
然后我去数据库发现记录的link似乎不对
比如https://t.me/c/256***/47*2***
实际link似乎应该为 256***  改为from_chat 字段的 109256***
最终为https://t.me/c/1091256***/472****
看了几个记录之后，发现中间那个群组id只会保留最后六位

1405404*** 变成了 404***

**Comment by lancer-wang** [comment]
![image](https://github.com/Taosky/telegram-search-bot/assets/69783837/ad9066d0-f207-496e-9868-a5a4e29842b7)

**Comment by Taosky** [comment]
这个是导入的历史记录吗？

**Comment by Taosky** [comment]
是用的userbot模式吗？应该是没有升级到super group。

` 人数较多的群组应该会自动升级, 手动升级需要将群组类型设置为Public（立即生效, 可再改回Private）

`msg_link = 'https://t.me/c/{}/{}'.format(str(chat_id)[4:], event.id)` [这行代码](https://github.com/Taosky/telegram-search-bot/blob/6b68516757a97ca5d86137bcc333969702ca73b0/userbot.py#L95C43-L95C49)去掉了chat id的前4位，因为super group实际的chat id是以`-100`开头的，而消息的链接没有`-100`。

**Comment by lancer-wang** [comment]
> 是用的userbot模式吗？应该是没有升级到super group。
> 
> `人数较多的群组应该会自动升级, 手动升级需要将群组类型设置为Public（立即生效, 可再改回Private）`
> 
> `msg_link = 'https://t.me/c/{}/{}'.format(str(chat_id)[4:], event.id)` [这行代码](https://github.com/Taosky/telegram-search-bot/blob/6b68516757a97ca5d86137bcc333969702ca73b0/userbot.py#L95C43-L95C49)去掉了chat id的前4位，因为super group实际的chat id是以`-100`开头的，而消息的链接没有`-100`。

我有用super group，改了好几次
