### ISSUE TITLE
改成webhook之后对机器人使用命令没反应

### ISSUE THREAD

**Issue by lancer-wang** [Taosky/telegram-search-bot#50]
但是数据记录正常

无论私聊还是到群组使用各种命令
机器人都没有反应

ps poll模式可以正常使用命令等

**Comment by lancer-wang** [comment]
![image](https://github.com/Taosky/telegram-search-bot/assets/69783837/21e98e08-d28b-49ee-b97f-df4de9d7f46e)
![image](https://github.com/Taosky/telegram-search-bot/assets/69783837/def67bbe-5a84-4c07-ad53-01473e04811d)

**Comment by lancer-wang** [comment]
怪就怪在，数据库记录数据是正常的

**Comment by Taosky** [comment]
没道理啊，`docker logs xxx `看下日志，发命令看看有没有收到。

如果是用的userbot模式的话，数据库消息是正常的，收消息是telethon单独处理的。可能就是caddy配置之类的问题，导致webhook没成功。

**Comment by lancer-wang** [comment]
> 没道理啊，`docker logs xxx `看下日志，发命令看看有没有收到。
> 
> 如果是用的userbot模式的话，数据库消息是正常的，收消息是telethon单独处理的。可能就是caddy配置之类的问题，导致webhook没成功。

日志那边没有反应，估计是没有收到

**Comment by lancer-wang** [comment]
> 没道理啊，`docker logs xxx `看下日志，发命令看看有没有收到。
> 
> 如果是用的userbot模式的话，数据库消息是正常的，收消息是telethon单独处理的。可能就是caddy配置之类的问题，导致webhook没成功。

caddy用的443 80 端口，因为占用所以我改成41443，然后做了个nginx反代

**Comment by Taosky** [comment]
> > 没道理啊，`docker logs xxx `看下日志，发命令看看有没有收到。
> > 如果是用的userbot模式的话，数据库消息是正常的，收消息是telethon单独处理的。可能就是caddy配置之类的问题，导致webhook没成功。
> 
> caddy用的443 80 端口，因为占用所以我改成41443，然后做了个nginx反代

docker-compose.yml 里面`HOOK_URL`应该要改一下，带端口，webhook初始化会把url发到telegram服务器。

**Comment by lancer-wang** [comment]
> > > 没道理啊，`docker logs xxx `看下日志，发命令看看有没有收到。
> > > 如果是用的userbot模式的话，数据库消息是正常的，收消息是telethon单独处理的。可能就是caddy配置之类的问题，导致webhook没成功。
> > 
> > 
> > caddy用的443 80 端口，因为占用所以我改成41443，然后做了个nginx反代
> 
> docker-compose.yml 里面`HOOK_URL`应该要改一下，带端口，webhook初始化会把url发到telegram服务器。

我试了下,端口只支持443 80 8443 
我改成  https://xxxxxx:443/test  还是不行

**Comment by Taosky** [comment]
> > > > 没道理啊，`docker logs xxx `看下日志，发命令看看有没有收到。
> > > > 如果是用的userbot模式的话，数据库消息是正常的，收消息是telethon单独处理的。可能就是caddy配置之类的问题，导致webhook没成功。
> > > 
> > > 
> > > caddy用的443 80 端口，因为占用所以我改成41443，然后做了个nginx反代
> > 
> > 
> > docker-compose.yml 里面`HOOK_URL`应该要改一下，带端口，webhook初始化会把url发到telegram服务器。
> 
> 我试了下,端口只支持443 80 8443 我改成 https://xxxxxx:443/test 还是不行

应该要改成`41443`，最终对外的端口。

**Comment by lancer-wang** [comment]
> > > > > 没道理啊，`docker logs xxx `看下日志，发命令看看有没有收到。
> > > > > 如果是用的userbot模式的话，数据库消息是正常的，收消息是telethon单独处理的。可能就是caddy配置之类的问题，导致webhook没成功。
> > > > 
> > > > 
> > > > caddy用的443 80 端口，因为占用所以我改成41443，然后做了个nginx反代
> > > 
> > > 
> > > docker-compose.yml 里面`HOOK_URL`应该要改一下，带端口，webhook初始化会把url发到telegram服务器。
> > 
> > 
> > 我试了下,端口只支持443 80 8443 我改成 https://xxxxxx:443/test 还是不行
> 
> 应该要改成`41443`，最终对外的端口。

改成这个会提示
![image](https://github.com/Taosky/telegram-search-bot/assets/69783837/c3a773bb-7639-424b-8fa7-2d3eb0a9469c)

**Comment by Taosky** [comment]
> > > > > > 没道理啊，`docker logs xxx `看下日志，发命令看看有没有收到。
> > > > > > 如果是用的userbot模式的话，数据库消息是正常的，收消息是telethon单独处理的。可能就是caddy配置之类的问题，导致webhook没成功。
> > > > > 
> > > > > 
> > > > > caddy用的443 80 端口，因为占用所以我改成41443，然后做了个nginx反代
> > > > 
> > > > 
> > > > docker-compose.yml 里面`HOOK_URL`应该要改一下，带端口，webhook初始化会把url发到telegram服务器。
> > > 
> > > 
> > > 我试了下,端口只支持443 80 8443 我改成 https://xxxxxx:443/test 还是不行
> > 
> > 
> > 应该要改成`41443`，最终对外的端口。
> 
> 改成这个会提示 ![image](https://user-images.githubusercontent.com/69783837/273870843-c3a773bb-7639-424b-8fa7-2d3eb0a9469c.png)

那没办法了，限制了...

**Comment by lancer-wang** [comment]
![image](https://github.com/Taosky/telegram-search-bot/assets/69783837/7c164220-2588-4bc7-815f-f1320dd98a72)

我对外的应该是443,服务器内部的才是4144341443

**Comment by Taosky** [comment]
> ![image](https://user-images.githubusercontent.com/69783837/273871066-7c164220-2588-4bc7-815f-f1320dd98a72.png)
> 
> 我对外的应该是443,服务器内部的才是41443

那应该没问题啊，手动访问试试能不能打开。

**Comment by lancer-wang** [comment]
> > ![image](https://user-images.githubusercontent.com/69783837/273871066-7c164220-2588-4bc7-815f-f1320dd98a72.png)
> > 我对外的应该是443,服务器内部的才是41443
> 
> 那应该没问题啊，手动访问试试能不能打开。

![image](https://github.com/Taosky/telegram-search-bot/assets/69783837/3f3adb09-5ce4-418c-aa58-758663cf2abc)

原来是这俩也得弄...

**Comment by Taosky** [comment]
> > > ![image](https://user-images.githubusercontent.com/69783837/273871066-7c164220-2588-4bc7-815f-f1320dd98a72.png)
> > > 我对外的应该是443,服务器内部的才是41443
> > 
> > 
> > 那应该没问题啊，手动访问试试能不能打开。
> 
> ![image](https://user-images.githubusercontent.com/69783837/273872034-3f3adb09-5ce4-418c-aa58-758663cf2abc.png)
> 
> 原来是这俩也得弄...

是的，有路径。
