### ISSUE TITLE
希望可以继续开发 ClashCS-Beta 项目

### ISSUE THREAD

**Issue by ArriettyQAQ** [Taosky/telegram-search-bot#6]
很抱歉无法在对应的项目下留言，只能留言这个项目下了。
目前 PC 端想找一个原生代码写的 Clash 前端实在是太难了，主要还是因为 Electron 写的程序太大了，而且比较占用系统资源，不够小巧，这个项目应该是目前仅存的使用 C# 写的项目了。
如果作者原意，还是希望这个项目能够继续开发下去，在此表示感谢。

**Comment by Taosky** [comment]
> 
> 
> 很抱歉无法在对应的项目下留言，只能留言这个项目下了。
> 目前 PC 端想找一个原生代码写的 Clash 前端实在是太难了，主要还是因为 Electron 写的程序太大了，而且比较占用系统资源，不够小巧，这个项目应该是目前仅存的使用 C# 写的项目了。
> 如果作者原意，还是希望这个项目能够继续开发下去，在此表示感谢。

不好意思，你可能留言错地方了，这个项目我闻所未闻。😅

**Comment by ArriettyQAQ** [comment]
> 
> 
> > 很抱歉无法在对应的项目下留言，只能留言这个项目下了。
> > 目前 PC 端想找一个原生代码写的 Clash 前端实在是太难了，主要还是因为 Electron 写的程序太大了，而且比较占用系统资源，不够小巧，这个项目应该是目前仅存的使用 C# 写的项目了。
> > 如果作者原意，还是希望这个项目能够继续开发下去，在此表示感谢。
> 
> 不好意思，你可能留言错地方了，这个项目我闻所未闻。😅

哈哈哈哈哈哈，卧槽，我可能是刚刚页面开的太多了，抱歉。

**Comment by Taosky** [comment]
> 
> 
> > > 很抱歉无法在对应的项目下留言，只能留言这个项目下了。
> > > 目前 PC 端想找一个原生代码写的 Clash 前端实在是太难了，主要还是因为 Electron 写的程序太大了，而且比较占用系统资源，不够小巧，这个项目应该是目前仅存的使用 C# 写的项目了。
> > > 如果作者原意，还是希望这个项目能够继续开发下去，在此表示感谢。
> > 
> > 
> > 不好意思，你可能留言错地方了，这个项目我闻所未闻。😅
> 
> 哈哈哈哈哈哈，卧槽，我可能是刚刚页面开的太多了，抱歉。

没事，那我关了这个Issue。
